name: ai
channels:
  - defaults
dependencies:
  - absl-py=2.1.0=py312hca03da5_0
  - alabaster=0.7.16=py312hca03da5_0
  - annotated-types=0.6.0=py312hca03da5_0
  - applaunchservices=0.3.0=py312hca03da5_0
  - appnope=0.1.3=py312hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h80987f9_0
  - arrow=1.2.3=py312hca03da5_1
  - astroid=2.14.2=py312hca03da5_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312hca03da5_0
  - atomicwrites=1.4.0=py_0
  - attrs=23.1.0=py312hca03da5_0
  - autopep8=2.0.4=pyhd3eb1b0_0
  - babel=2.11.0=py312hca03da5_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=24.4.2=py312hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.7=py312ha86b861_0
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - brotli-python=1.0.9=py312h313beb8_8
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2024.3.11=hca03da5_0
  - cairo=1.16.0=h302bd0f_5
  - certifi=2024.6.2=py312hca03da5_0
  - chardet=4.0.0=py312hca03da5_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py312hca03da5_0
  - cloudpickle=2.2.1=py312hca03da5_0
  - colorama=0.4.6=py312hca03da5_0
  - comm=0.2.1=py312hca03da5_0
  - contourpy=1.2.0=py312h48ca7d4_0
  - cookiecutter=2.6.0=py312hca03da5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9131b1a_1
  - debugpy=1.6.7=py312h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - distro=1.9.0=py312hca03da5_0
  - dm-tree=0.1.7=py312h313beb8_1
  - docstring-to-markdown=0.11=py312hca03da5_0
  - docutils=0.18.1=py312hca03da5_3
  - eigen=3.4.0=h48ca7d4_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.2=h313beb8_0
  - ffmpeg=4.2.2=h04105a8_0
  - filelock=3.13.1=py312hca03da5_0
  - flake8=7.0.0=py312hca03da5_0
  - fontconfig=2.14.1=hee714a5_2
  - fonttools=4.51.0=py312h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - fsspec=2024.3.1=py312hca03da5_0
  - gettext=0.21.0=h13f89a0_1
  - giflib=5.2.1=h80987f9_3
  - glib=2.78.4=h313beb8_0
  - glib-tools=2.78.4=h313beb8_0
  - gmp=6.2.1=hc377ac9_3
  - gnutls=3.6.15=h887c41c_0
  - graphite2=1.3.14=hc377ac9_1
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - h11=0.14.0=py312hca03da5_0
  - h5py=3.11.0=py312haac6407_0
  - harfbuzz=4.3.0=he9eebac_1
  - hdf5=1.12.1=h05c076b_3
  - httpcore=1.0.2=py312hca03da5_0
  - icu=68.1=hc377ac9_0
  - idna=3.7=py312hca03da5_0
  - imagesize=1.4.1=py312hca03da5_0
  - importlib-metadata=7.0.1=py312hca03da5_0
  - inflection=0.5.1=py312hca03da5_1
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.28.0=py312hca03da5_0
  - ipython=8.25.0=py312hca03da5_0
  - isort=5.13.2=py312hca03da5_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.18.1=py312hca03da5_1
  - jellyfish=1.0.1=py312h15d1925_0
  - joblib=1.4.2=py312hca03da5_0
  - jpeg=9e=h80987f9_1
  - jsonschema-specifications=2023.7.1=py312hca03da5_0
  - jupyter-lsp=2.2.0=py312hca03da5_0
  - jupyter_client=8.6.0=py312hca03da5_0
  - jupyter_core=5.7.2=py312hca03da5_0
  - jupyter_events=0.10.0=py312hca03da5_0
  - jupyter_server=2.14.1=py312hca03da5_0
  - jupyter_server_terminals=0.4.4=py312hca03da5_1
  - jupyterlab=4.0.11=py312hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py312hca03da5_0
  - keras=3.0.5=py312hca03da5_0
  - keyring=24.3.1=py312hca03da5_0
  - kiwisolver=1.4.4=py312h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lame=3.100=h1a28f6b_0
  - lazy-object-proxy=1.10.0=py312h80987f9_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libclang=14.0.6=default_h1b80db6_1
  - libclang13=14.0.6=default_h24352ff_1
  - libcurl=8.7.1=h3e2b118_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.78.4=h0a96307_0
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.4=h80987f9_0
  - libllvm14=14.0.6=h7ec7a93_3
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libopus=1.3=h1a28f6b_1
  - libpng=1.6.39=h80987f9_0
  - libpq=12.17=h02f6b3c_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libsodium=1.0.18=h1a28f6b_0
  - libspatialindex=1.9.3=hc377ac9_0
  - libssh2=1.11.0=h3e2b118_0
  - libtasn1=4.19.0=h80987f9_0
  - libtiff=4.5.1=h313beb8_0
  - libunistring=0.9.10=h1a28f6b_0
  - libvpx=1.10.0=hc377ac9_0
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxml2=2.10.4=h372ba2a_0
  - libxslt=1.1.37=habca612_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markdown-it-py=2.2.0=py312hca03da5_1
  - markupsafe=2.1.3=py312h80987f9_0
  - matplotlib-base=3.8.4=py312hd77ebd4_0
  - matplotlib-inline=0.1.6=py312hca03da5_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdurl=0.1.0=py312hca03da5_0
  - mistune=2.0.4=py312hca03da5_0
  - ml_dtypes=0.3.1=py312hd77ebd4_0
  - more-itertools=10.1.0=py312hca03da5_0
  - mpmath=1.3.0=py312hca03da5_0
  - mypy_extensions=1.0.0=py312hca03da5_0
  - mysql=5.7.24=ha71a6ea_2
  - namex=0.0.7=py312hca03da5_0
  - nbclient=0.8.0=py312hca03da5_0
  - nbconvert=7.10.0=py312hca03da5_0
  - nbformat=5.9.2=py312hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py312hca03da5_0
  - nettle=3.7.3=h84b5d62_1
  - networkx=3.3=py312hca03da5_0
  - nltk=3.8.1=py312hca03da5_0
  - notebook=7.0.8=py312hca03da5_0
  - notebook-shim=0.2.3=py312hca03da5_0
  - numexpr=2.8.7=py312h0f3ea24_0
  - numpy=1.26.4=py312h7f4fdc5_0
  - numpy-base=1.26.4=py312he047099_0
  - numpydoc=1.7.0=py312hca03da5_0
  - opencv=4.6.0=py312h2e348d3_5
  - openh264=1.8.0=h98b2900_0
  - openjpeg=2.4.0=h0ed58ac_1
  - openssl=3.0.14=h80987f9_0
  - overrides=7.4.0=py312hca03da5_0
  - packaging=23.2=py312hca03da5_0
  - pandas=2.2.2=py312hd77ebd4_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.10.3=py312hca03da5_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=24.0=py312hca03da5_0
  - pixman=0.40.0=h1a28f6b_0
  - platformdirs=3.10.0=py312hca03da5_0
  - pluggy=1.0.0=py312hca03da5_1
  - ply=3.11=py312hca03da5_1
  - prometheus_client=0.14.1=py312hca03da5_0
  - prompt-toolkit=3.0.43=py312hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h80987f9_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycodestyle=2.11.1=py312hca03da5_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.3.0=py312hca03da5_0
  - pyflakes=3.2.0=py312hca03da5_0
  - pygments=2.15.1=py312hca03da5_1
  - pylint=2.16.2=py312hca03da5_0
  - pylint-venv=3.0.3=py312hca03da5_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pyobjc-core=10.1=py312h80987f9_0
  - pyobjc-framework-cocoa=10.1=py312hb094c41_0
  - pyobjc-framework-coreservices=10.1=py312hdd8dd1f_0
  - pyobjc-framework-fsevents=10.1=py312hca03da5_0
  - pyparsing=3.0.9=py312hca03da5_0
  - pyqt=5.15.10=py312h313beb8_0
  - pyqt5-sip=12.13.0=py312h80987f9_0
  - pyqtwebengine=5.15.10=py312h313beb8_0
  - pysocks=1.7.1=py312hca03da5_0
  - python=3.12.4=h99e199e_1
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-fastjsonschema=2.16.2=py312hca03da5_0
  - python-json-logger=2.0.7=py312hca03da5_0
  - python-lsp-black=2.0.0=py312hca03da5_0
  - python-lsp-jsonrpc=1.1.2=pyhd3eb1b0_0
  - python-lsp-server=1.10.0=py312hca03da5_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python.app=3=py312h80987f9_0
  - pytoolconfig=1.2.6=py312hca03da5_0
  - pytz=2024.1=py312hca03da5_0
  - pyyaml=6.0.1=py312h80987f9_0
  - pyzmq=25.1.2=py312h313beb8_0
  - qdarkstyle=3.2.3=pyhd3eb1b0_0
  - qstylizer=0.2.2=py312hca03da5_0
  - qt-main=5.15.2=h9b4df51_9
  - qt-webengine=5.15.9=h2903aaf_7
  - qtawesome=1.2.2=py312hca03da5_0
  - qtconsole=5.5.1=py312hca03da5_0
  - qtpy=2.4.1=py312hca03da5_0
  - qtwebkit=5.212=h19f419d_5
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py312hca03da5_0
  - rfc3339-validator=0.1.4=py312hca03da5_0
  - rfc3986-validator=0.1.1=py312hca03da5_0
  - rope=1.12.0=py312hca03da5_0
  - rpds-py=0.10.6=py312hf0e4da2_0
  - rtree=1.0.1=py312hca03da5_0
  - seaborn=0.13.2=py312hca03da5_0
  - send2trash=1.8.2=py312hca03da5_0
  - setuptools=69.5.1=py312hca03da5_0
  - sip=6.7.12=py312h313beb8_0
  - six=1.16.0=pyhd3eb1b0_1
  - sleef=3.5.1=h80987f9_2
  - sniffio=1.3.0=py312hca03da5_0
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py312hca03da5_0
  - sphinx=7.3.7=py312hca03da5_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.10=py312hca03da5_0
  - spyder=5.5.1=py312hca03da5_0
  - spyder-kernels=2.5.0=py312hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tabulate=0.9.0=py312hca03da5_0
  - terminado=0.17.1=py312hca03da5_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss2=1.2.1=py312hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - tomlkit=0.11.1=py312hca03da5_0
  - tornado=6.4.1=py312h80987f9_0
  - tqdm=4.66.4=py312h989b03a_0
  - traitlets=5.14.3=py312hca03da5_0
  - tzdata=2024a=h04d1e81_0
  - ujson=5.10.0=py312h313beb8_0
  - unicodedata2=15.1.0=py312h80987f9_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=2.2.2=py312hca03da5_0
  - watchdog=4.0.1=py312h80987f9_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312hca03da5_2
  - websocket-client=1.8.0=py312hca03da5_0
  - whatthepatch=1.0.2=py312hca03da5_0
  - wheel=0.43.0=py312hca03da5_0
  - wrapt=1.14.1=py312h80987f9_0
  - wurlitzer=3.0.2=py312hca03da5_0
  - x264=1!152.20180806=h1a28f6b_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - yapf=0.40.2=py312hca03da5_0
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.17.0=py312hca03da5_0
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.5=hd90d995_2
  - pip:
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - anthropic==0.69.0
      - anyio==4.11.0
      - appdirs==1.4.4
      - backoff==2.2.1
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.2
      - blinker==1.9.0
      - browserbase==1.4.0
      - build==1.3.0
      - cachetools==6.2.1
      - cffi==2.0.0
      - chromadb==1.1.1
      - clip==1.0
      - coloredlogs==15.0.1
      - crewai==0.203.0
      - crewai-tools==0.76.0
      - cryptography==46.0.2
      - dataclasses-json==0.6.7
      - datetime==5.5
      - deprecation==2.1.0
      - dill==0.2.7.1
      - diskcache==5.6.3
      - dnspython==2.8.0
      - docker==7.1.0
      - docstring-parser==0.17.0
      - durationpy==0.10
      - email-validator==2.3.0
      - et-xmlfile==2.0.0
      - face-alignment==1.4.1
      - fastapi==0.119.1
      - fastapi-cli==0.0.14
      - fastapi-cloud-cli==0.3.1
      - filetype==1.2.0
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - ftfy==6.3.1
      - geographiclib==2.0
      - geopy==2.4.1
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.26.0
      - google-api-python-client==2.184.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.0
      - google-genai==1.43.0
      - google-generativeai==0.8.5
      - google-search-results==2.4.2
      - googleapis-common-protos==1.70.0
      - gotrue==2.12.4
      - greenlet==3.2.4
      - grpcio==1.75.1
      - grpcio-status==1.71.2
      - h2==4.3.0
      - hf-xet==1.1.10
      - hpack==4.1.0
      - httplib2==0.31.0
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.35.3
      - humanfriendly==10.0
      - hyperframe==6.1.0
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - instructor==1.11.3
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jira==3.10.5
      - jiter==0.10.0
      - json-repair==0.25.2
      - json5==0.12.1
      - jsonpatch==1.33
      - jsonpickle==4.1.1
      - jsonpointer==3.0.0
      - jsonref==1.1.0
      - jsonschema==4.25.1
      - kaggle==1.6.17
      - kubernetes==34.1.0
      - lance-namespace==0.0.18
      - lance-namespace-urllib3-client==0.0.18
      - lancedb==0.25.2
      - langchain==0.3.27
      - langchain-anthropic==0.3.22
      - langchain-community==0.3.31
      - langchain-core==0.3.79
      - langchain-google-genai==2.0.10
      - langchain-litellm==0.2.3
      - langchain-text-splitters==0.3.11
      - langgraph==1.0.6
      - langgraph-checkpoint==2.1.2
      - langgraph-prebuilt==0.6.4
      - langgraph-sdk==0.3.2
      - langsmith==0.4.43
      - lazy-loader==0.4
      - litellm==1.74.9
      - llvmlite==0.44.0
      - lxml==6.0.2
      - marshmallow==3.26.1
      - mmh3==5.2.0
      - multidict==6.7.0
      - narwhals==2.1.2
      - numba==0.61.0
      - oauthlib==3.3.1
      - onnxruntime==1.23.1
      - openai==1.109.1
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - opentelemetry-api==1.37.0
      - opentelemetry-exporter-otlp-proto-common==1.37.0
      - opentelemetry-exporter-otlp-proto-grpc==1.37.0
      - opentelemetry-exporter-otlp-proto-http==1.37.0
      - opentelemetry-proto==1.37.0
      - opentelemetry-sdk==1.37.0
      - opentelemetry-semantic-conventions==0.58b0
      - orjson==3.11.3
      - ormsgpack==1.11.0
      - patsy==1.0.1
      - pdfminer-six==20250506
      - pdfplumber==0.11.7
      - pillow==9.5.0
      - playwright==1.55.0
      - plotly==6.3.0
      - portalocker==2.7.0
      - postgrest==2.22.0
      - posthog==5.4.0
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psycopg2==2.9.11
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - pydantic-extra-types==2.10.6
      - pydantic-settings==2.11.0
      - pyee==13.0.0
      - pyjwt==2.10.1
      - pylance==0.38.2
      - pymupdf==1.26.5
      - pypdf==6.1.1
      - pypdfium2==4.30.0
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - python-docx==1.2.0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytube==15.0.0
      - pyvis==0.3.2
      - realtime==2.22.0
      - regex==2025.9.18
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rich-toolkit==0.15.1
      - rignore==0.7.1
      - rsa==4.9.1
      - scikit-image==0.24.0
      - scikit-learn==1.7.1
      - scipy==1.15.2
      - sentry-sdk==2.42.1
      - serpapi==0.1.5
      - shellingham==1.5.4
      - sqlalchemy==2.0.44
      - stagehand==0.5.4
      - starlette==0.48.0
      - statsmodels==0.14.5
      - storage3==2.22.0
      - strenum==0.4.15
      - supabase==2.22.0
      - supabase-auth==2.22.0
      - supabase-functions==2.22.0
      - sympy==1.13.1
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tifffile==2025.3.13
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - tomli-w==1.2.0
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - typer==0.19.2
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - uritemplate==4.2.0
      - uv==0.9.2
      - uvicorn==0.37.0
      - uvloop==0.21.0
      - watchfiles==1.1.0
      - websockets==15.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - youtube-transcript-api==1.2.2
      - zope-interface==8.0.1
      - zstandard==0.25.0
prefix: /opt/anaconda3/envs/ai
